### ISSUE TITLE
[Suggestion] add an option to one click eat to eat continuously if the eating key is held 

### ISSUE THREAD

**Issue by Radial2250** [Bennooo/banana-for-everyone#10]
### Describe the feature

.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by RickyTheRacc** [comment]
Or just manually gap as god intended

Jokes aside this module is genuinely robotic, please just manually gap it's so much better in every way
