### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Wet33** [Bennooo/banana-for-everyone#11]
### Describe the feature

pls add AUTO BED CRAFT and penis esp

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by RickyTheRacc** [comment]
Keep yourself _extremely_ safe
