### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dababya** [Bennooo/banana-for-everyone#12]
### Describe the Bug

When i run Meteor 0.5.0 and Banana plus on fabric 1.19 my game crashes
[crash-2022-06-19_19.04.18-client.txt](https://github.com/Bennooo/banana-for-everyone/files/8935785/crash-2022-06-19_19.04.18-client.txt)
Here is the crash text 

### Steps to Reproduce

```bash
When i run Meteor 0.5.0 and Banana plus on fabric 1.19 my game crashes
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RedCarlos26** [comment]
We're you running meteor and banana+ without any other meteor addon?

**Comment by Dababya** [comment]
> 

yeah i didnt run any other addon
