### ISSUE TITLE
[Bug] Crash when trying to add WelcomeHud to HUD

### ISSUE THREAD

**Issue by RedCarlos26** [Bennooo/banana-for-everyone#16]
### Describe the Bug

[crash-2022-07-16_21.36.16-client.txt](https://github.com/Bennooo/banana-for-everyone/files/9126890/crash-2022-07-16_21.36.16-client.txt)

### Steps to Reproduce

```bash
- Open HUD editor
- Try adding WelcomeHud
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RickyTheRacc** [comment]
Fixed in #18
