### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by 60YzArC** [Bennooo/banana-for-everyone#21]
### Describe the Bug

needs a update for the latest version of meteor

### Steps to Reproduce

```bash
1. open mc
2. game crash
3. cry :(
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RickyTheRacc** [comment]
Already updated
