### ISSUE TITLE
[Bug] joining/creating singleplayer worlds with b+ makes you get stuck on the "loading terrain" screen

### ISSUE THREAD

**Issue by Radial2250** [Bennooo/banana-for-everyone#25]
### Describe the Bug

.

### Steps to Reproduce

```bash
.
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RickyTheRacc** [comment]
Known issue, but I honestly have no idea how to fix it. Joining another server and toggling everything off and then rejoining seems to work in some cases
