### ISSUE TITLE
[Bug] Banana+ kills/deaths starscript is fucked

### ISSUE THREAD

**Issue by I-Got-You-Dead** [Bennooo/banana-for-everyone#26]
### Describe the Bug

💀💀💀

### Steps to Reproduce

```bash
Just get some kills/deaths with the hud elements enabled
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RedCarlos26** [comment]
Works for me

**Comment by I-Got-You-Dead** [comment]
What version you on?

**Comment by RedCarlos26** [comment]
Latest

**Comment by RickyTheRacc** [comment]
Can't reproduce

**Comment by I-Got-You-Dead** [comment]
I’ll do some more testing and see if I can send a vid
