### ISSUE TITLE
AutoCity fix 

### ISSUE THREAD

**Issue by Dasyat1s** [Bennooo/banana-for-everyone#5]
The auto city auto switches to the pick and stays this way. Maybe could you change it in order to make it switch at the last moment (+fixing the auto toggle issue : the autocity ain't toggling off after breaking 1 block and stays on even tho it isn't trying to break any other blocks (ain't an auto auto issue, turned the auto city option off))

**Comment by RickyTheRacc** [comment]
The toggling issues likely arose from some changes I did yesterday night. I'll look into fixing those when I get home, but to be totally honest this module needs an entire rewrite at some point and most people are better off not using it regardless lol

**Comment by RickyTheRacc** [comment]
Bruhh looking at the code it doesn't seem like auto toggle ever *did* work... there is nothing to toggle after breaking the target block, only if it doesn't meet parameters for other settings, this is a real necro moment
