### ISSUE TITLE
[Suggestion] rename the "banana" in the module category header in the gui to "B+" or "B+2" so the columns aren't so wide

### ISSUE THREAD

**Issue by Radial2250** [Bennooo/banana-for-everyone#9]
### Describe the feature

.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by RickyTheRacc** [comment]
:cat_no:
